services:
- type: web
  name: foto-owl-api
  runtime: python
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
  envVars:
    - key: S3_ENDPOINT
    - key: S3_KEY
    - key: S3_SECRET
    - key: S3_BUCKET
    - key: GOOGLE_API_KEY
