services:
  - type: web
    name: foto-owl-frontend
    env: docker
    dockerfilePath: ./Dockerfile.frontend
    plan: free

  - type: web
    name: foto-owl-api
    env: docker
    dockerfilePath: ./api-gateway/Dockerfile
    plan: free
